-- Generated by load_ganado_rojo.py — DO NOT EDIT BY HAND, regenerate instead.
-- Source file: ganado_rojo.csv
-- Total rows: 201 (52 con arete, 149 sin arete)
--
-- ⚠️ NOT SAFE TO RE-RUN. Tagged animals upsert safely via rfid_siniiga (UNIQUE).
-- Untagged animals (INSERT only, no natural key) WILL duplicate if this file runs
-- twice against the same environment. Same caution as load_birth_events.py.
--
-- production_unit_id and leased_site_id are left NULL for all 201 animals:
-- client confirmed (2026-08-05) these belong to 'La Bendición' but could stand
-- on any of Alejandro's 3 registered units. Not guessed here.
BEGIN;

-- Fila 1 · VACA · fuego 1828 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1828-1', '1828', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 2 · VACA · fuego 2379 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2379-2', '2379', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "ORIGINAL: arete transcrito como 072005 (6 digitos, incompleto - le falta el numero grande). Cargado sin arete usando el quemado. Verificar arete real contra el animal fisico."}'::jsonb);

-- Fila 3 · VACA · fuego 2210 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2210-3', '2210', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 4 · VACA · fuego 1882 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1882-4', '1882', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 5 · VACA · fuego 2053 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2053-5', '2053', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 6 · VACA · fuego 1705 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1705-6', '1705', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 7 · VACA · fuego 1538 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1538-7', '1538', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 8 · VACA · fuego 1704 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1704-8', '1704', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 9 · VACA · fuego 1821 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1821-9', '1821', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 10 · VACA · fuego 1683 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1683-10', '1683', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 11 · VACA · fuego 23106 · arete 0721391932
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0721391932', '23106', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 12 · VACA · fuego 2367 · arete 0720661251
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661251', '2367', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 13 · VACA · fuego 2037 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2037-13', '2037', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 14 · VACA · fuego 1537 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1537-14', '1537', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 15 · VACA · fuego 1778 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1778-15', '1778', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 16 · VACA · fuego 1450 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1450-16', '1450', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 17 · VACA · fuego 2010 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2010-17', '2010', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 18 · VACA · fuego 1973 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1973-18', '1973', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 19 · VACA · fuego 1993 · arete 0715295469
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0715295469', '1993', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 20 · VACA · fuego 1843 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1843-20', '1843', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 21 · VACA · fuego 2571 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2571-21', '2571', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 22 · VACA · fuego 2311 · arete 0720053379
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053379', '2311', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 23 · VACA · fuego 21124 · arete 0719128594
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0719128594', '21124', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 24 · VACA · fuego 1762 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1762-24', '1762', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 25 · VACA · fuego 2105 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2105-25', '2105', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 26 · VACA · fuego 1837 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1837-26', '1837', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 27 · VACA · fuego 2124 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2124-27', '2124', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 28 · VACA · fuego 2365 · arete 0722090575
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0722090575', '2365', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 29 · VACA · fuego 2421 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2421-29', '2421', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 30 · VACA · fuego 2295 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2295-30', '2295', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 31 · VACA · fuego 1875 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1875-31', '1875', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 32 · VACA · fuego 1969 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1969-32', '1969', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 33 · VACA · fuego 1990 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1990-33', '1990', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 34 · VACA · fuego 1841 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1841-34', '1841', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 35 · VACA · fuego 2297 · arete 0720152227
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152227', '2297', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 36 · VACA · fuego 2411 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2411-36', '2411', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 37 · VACA · fuego 1660 · arete 0720053203
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053203', '1660', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 38 · VACA · fuego 1757 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1757-38', '1757', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 39 · VACA · fuego 1852 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1852-39', '1852', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 40 · VACA · fuego 1753 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1753-40', '1753', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 41 · VACA · fuego 1710 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1710-41', '1710', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 42 · VACA · fuego 1901 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1901-42', '1901', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "QUEMADO DUPLICADO dentro del lote (ver tambien fila 170) - sin arete que distinga, verificar en campo si son dos animales reales o el mismo anotado dos veces"}'::jsonb);

-- Fila 43 · VACA · fuego 2122 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2122-43', '2122', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 44 · VACA · fuego 21116 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-21116-44', '21116', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 45 · VACA · fuego 22111 · arete 0720661234
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661234', '22111', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 46 · VACA · fuego 2114 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2114-46', '2114', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 47 · VACA · fuego 1557 · arete 0720152498
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152498', '1557', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 48 · VACA · fuego 1838 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1838-48', '1838', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 49 · VACA · fuego 1914 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1914-49', '1914', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 50 · VACA · fuego 1936 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1936-50', '1936', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 51 · VACA · fuego 1653 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1653-51', '1653', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 52 · VACA · fuego 21127 · arete 0718436886
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0718436886', '21127', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 53 · VACA · fuego 1899 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1899-53', '1899', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 54 · VACA · fuego 2410 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2410-54', '2410', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 55 · VACA · fuego 1428 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1428-55', '1428', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 56 · VACA · fuego 1646 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1646-56', '1646', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 57 · VACA · fuego 2229 · arete 0720053305
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053305', '2229', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 58 · VACA · fuego 2215 · arete 0720053381
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053381', '2215', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "Quemado 2215 tambien aparece en fila 79 con arete distinto (0722090627) - dos animales reales, sin conflicto real ya que ambos tienen arete propio"}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 59 · VACA · fuego 2389 · arete 0721391899
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0721391899', '2389', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 60 · VACA · fuego 03 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-03-60', '03', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "Quemado de solo 2 digitos - inusual, verificar si es correcto"}'::jsonb);

-- Fila 61 · VACA · fuego 2307 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2307-61', '2307', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 62 · VACA · fuego 2239 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2239-62', '2239', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 63 · VACA · fuego 1445 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1445-63', '1445', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 64 · VACA · fuego 2206 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2206-64', '2206', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 65 · VACA · fuego 19122 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19122-65', '19122', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 66 · VACA · fuego 1531 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1531-66', '1531', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 67 · VACA · fuego 2254 · arete 0719376074
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0719376074', '2254', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 68 · VACA · fuego 19127 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19127-68', '19127', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 69 · VACA · fuego 1879 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1879-69', '1879', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 70 · VACA · fuego 1706 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1706-70', '1706', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 71 · VACA · fuego 1554 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1554-71', '1554', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 72 · VACA · fuego 2455 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2455-72', '2455', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 73 · VACA · fuego 1729 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1729-73', '1729', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 74 · VACA · fuego 1507 · arete 0720053370
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053370', '1507', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 75 · VACA · fuego 21120 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-21120-75', '21120', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 76 · VACA · fuego 1786 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1786-76', '1786', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 77 · VACA · fuego 1966 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1966-77', '1966', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 78 · VACA · fuego 21134 · arete 0718127727
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0718127727', '21134', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 79 · VACA · fuego 2215 · arete 0722090627
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0722090627', '2215', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "Quemado 2215 tambien aparece en fila 58 con arete distinto (0720053381) - dos animales reales, sin conflicto real ya que ambos tienen arete propio"}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 80 · VACA · fuego 1816 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1816-80', '1816', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 81 · VACA · fuego 1426 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1426-81', '1426', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 82 · VACA · fuego 1703 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1703-82', '1703', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 83 · VACA · fuego 1811 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1811-83', '1811', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 84 · VACA · fuego 1912 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1912-84', '1912', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 85 · VACA · fuego 1894 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1894-85', '1894', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 86 · VACA · fuego 1558 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1558-86', '1558', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 87 · VACA · fuego 1823 · arete 0720053210
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053210', '1823', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 88 · VACA · fuego 1712 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1712-88', '1712', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 89 · VACA · fuego 1960 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1960-89', '1960', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 90 · VACA · fuego 2224 · arete 0720053273
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053273', '2224', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 91 · VACA · fuego 2228 · arete 0719128554
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0719128554', '2228', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 92 · VACA · fuego 2553 · arete 0721391942
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0721391942', '2553', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 93 · VACA · fuego 1874 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1874-93', '1874', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 94 · VACA · fuego 19120 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19120-94', '19120', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 95 · VACA · fuego 1941 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1941-95', '1941', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 96 · VACA · fuego 1996 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1996-96', '1996', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 97 · VACA · fuego 1730 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1730-97', '1730', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 98 · VACA · fuego 1877 · arete 0720121910
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720121910', '1877', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 99 · VACA · fuego 2412 · arete 0722090672
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0722090672', '2412', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 100 · VACA · fuego 19105 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19105-100', '19105', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 101 · VACA · fuego 1923 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1923-101', '1923', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 102 · VACA · fuego 2431 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2431-102', '2431', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 103 · VACA · fuego 2288 · arete 0720661546
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661546', '2288', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 104 · VACA · fuego 2244 · arete 0720053348
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053348', '2244', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 105 · VACA · fuego 2005 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2005-105', '2005', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 106 · VACA · fuego 1870 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1870-106', '1870', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "QUEMADO DUPLICADO dentro del lote (ver tambien fila 121) - sin arete que distinga, verificar en campo"}'::jsonb);

-- Fila 107 · VACA · fuego 1795 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1795-107', '1795', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 108 · VACA · fuego 1714 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1714-108', '1714', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 109 · VACA · fuego 1742 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1742-109', '1742', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 110 · VACA · fuego 1527 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1527-110', '1527', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 111 · VACA · fuego 1780 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1780-111', '1780', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 112 · VACA · fuego 1654 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1654-112', '1654', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 113 · VACA · fuego 1977 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1977-113', '1977', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 114 · VACA · fuego 1744 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1744-114', '1744', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 115 · VACA · fuego 1363 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1363-115', '1363', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 116 · VACA · fuego 1668 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1668-116', '1668', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 117 · VACA · fuego 1887 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1887-117', '1887', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 118 · VACA · fuego 1756 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1756-118', '1756', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 119 · VACA · fuego 1540 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1540-119', '1540', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 120 · VACA · fuego 2047 · arete 0717184328
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0717184328', '2047', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 121 · VACA · fuego 1870 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1870-121', '1870', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "QUEMADO DUPLICADO dentro del lote (ver tambien fila 106) - sin arete que distinga, verificar en campo"}'::jsonb);

-- Fila 122 · VACA · fuego 1419 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1419-122', '1419', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 123 · VACA · fuego 1891 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1891-123', '1891', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 124 · VACA · fuego 21131 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-21131-124', '21131', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 125 · VACA · fuego 1929 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1929-125', '1929', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 126 · VACA · fuego 1883 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1883-126', '1883', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 127 · VACA · fuego 1878 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1878-127', '1878', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 128 · VACA · fuego 1643 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1643-128', '1643', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 129 · VACA · fuego 1755 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1755-129', '1755', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 130 · VACA · fuego 1774 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1774-130', '1774', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 131 · VACA · fuego 1699 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1699-131', '1699', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 132 · VACA · fuego 1513 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1513-132', '1513', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 133 · TORO · fuego 12 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-12-133', '12', 'TORO', 'REPRODUCCION', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "Numero de control interno consecutivo de toros (secuencia separada de las vacas). Original en libreta: ''12 TORO''."}'::jsonb);

-- Fila 134 · VACA · fuego 1867 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1867-134', '1867', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 135 · VACA · fuego 1723 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1723-135', '1723', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 136 · VACA · fuego 19102 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19102-136', '19102', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 137 · VACA · fuego 2062 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2062-137', '2062', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 138 · VACA · fuego 24101 · arete 0722090602
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0722090602', '24101', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 139 · VACA · fuego 19106 · arete 0715690197
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0715690197', '19106', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 140 · VACA · fuego 1520 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1520-140', '1520', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 141 · VACA · fuego 2534 · arete 0720661231
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661231', '2534', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 142 · VACA · fuego 1666 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1666-142', '1666', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 143 · VACA · fuego 1733 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1733-143', '1733', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 144 · VACA · fuego 2170 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2170-144', '2170', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 145 · VACA · fuego 1713 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1713-145', '1713', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 146 · VACA · fuego 2167 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2167-146', '2167', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 147 · VACA · fuego 2207 · arete 0720053271
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053271', '2207', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 148 · VACA · fuego 1746 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1746-148', '1746', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 149 · VACA · fuego 2191 · arete 0718436811
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0718436811', '2191', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 150 · VACA · fuego 1662 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1662-150', '1662', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 151 · VACA · fuego 1720 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1720-151', '1720', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 152 · VACA · fuego 1454 · arete 0720121969
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720121969', '1454', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 153 · VACA · fuego 2290 · arete 0720661212
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661212', '2290', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 154 · VACA · fuego 1411 · arete 0720152485
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152485', '1411', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 155 · VACA · fuego 19137 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-19137-155', '19137', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 156 · VACA · fuego 2225 · arete 0720053317
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053317', '2225', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 157 · VACA · fuego 1818 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1818-157', '1818', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 158 · VACA · fuego 2336 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2336-158', '2336', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 159 · VACA · fuego 2142 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2142-159', '2142', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 160 · VACA · fuego 2346 · arete 0720661250
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661250', '2346', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 161 · VACA · fuego 19124 · arete 0715690247
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0715690247', '19124', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 162 · VACA · fuego 23106 · arete 0722090584
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0722090584', '23106', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "Quemado 23106 tambien aparece en fila 11 con arete distinto (0721391932) - dos animales reales"}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 163 · VACA · fuego 2347 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2347-163', '2347', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 164 · VACA · fuego 1686 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1686-164', '1686', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 165 · VACA · fuego 1794 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1794-165', '1794', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 166 · VACA · fuego 1678 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1678-166', '1678', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 167 · VACA · fuego 1732 · arete 0720152506
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152506', '1732', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 168 · VACA · fuego 22105 · arete 0720661213
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661213', '22105', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 169 · VACA · fuego 2345 · arete 0720661235
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720661235', '2345', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 170 · VACA · fuego 1901 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1901-170', '1901', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true, "nota_transcripcion": "QUEMADO DUPLICADO dentro del lote (ver tambien fila 42) - sin arete que distinga, verificar en campo"}'::jsonb);

-- Fila 171 · VACA · fuego 1621 · arete 0720152490
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152490', '1621', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 172 · VACA · fuego 2021 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2021-172', '2021', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 173 · VACA · fuego 1779 · arete 0720152442
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152442', '1779', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 174 · VACA · fuego 1422 · arete 0720152511
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152511', '1422', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 175 · VACA · fuego 1803 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1803-175', '1803', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 176 · VACA · fuego 1908 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1908-176', '1908', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 177 · VACA · fuego 1452 · arete 0720152484
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152484', '1452', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 178 · VACA · fuego 1722 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1722-178', '1722', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 179 · VACA · fuego 1958 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1958-179', '1958', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 180 · VACA · fuego 2279 · arete 0720152228
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152228', '2279', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 181 · VACA · fuego 1925 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1925-181', '1925', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 182 · VACA · fuego 1649 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1649-182', '1649', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 183 · VACA · fuego 2387 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2387-183', '2387', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 184 · VACA · fuego 1986 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1986-184', '1986', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 185 · VACA · fuego 1889 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1889-185', '1889', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 186 · VACA · fuego 2014 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2014-186', '2014', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 187 · VACA · fuego 2182 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2182-187', '2182', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 188 · VACA · fuego 1523 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1523-188', '1523', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 189 · VACA · fuego 2391 · arete 0721392931
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0721392931', '2391', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 190 · VACA · fuego 2066 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2066-190', '2066', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 191 · VACA · fuego 1166 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1166-191', '1166', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 192 · VACA · fuego 1709 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1709-192', '1709', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 193 · VACA · fuego 1447 · arete 0720152486
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720152486', '1447', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 194 · VACA · fuego 1775 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1775-194', '1775', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 195 · VACA · fuego 1928 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1928-195', '1928', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 196 · VACA · fuego 1839 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-1839-196', '1839', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 197 · VACA · fuego 2221 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-2221-197', '2221', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 198 · VACA · fuego 2293 · arete 0720053386
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053386', '2293', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 199 · VACA · fuego 1948 · arete 0715295525
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0715295525', '1948', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

-- Fila 200 · VACA · fuego 21141 · SIN ARETE
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, 'S/N-21141-200', '21141', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb);

-- Fila 201 · VACA · fuego 2227 · arete 0720053272
INSERT INTO cattle_livestock (tenant_id, rfid_siniiga, numero_fuego, category, business_model, current_status, species, current_weight_kg, brand_id, metadata) VALUES (5, '0720053272', '2227', 'VACA', 'CRIA', 'ACTIVO', 'BOVINO', 0, (SELECT id FROM brand_registrations WHERE upper(brand_code) = upper('R') LIMIT 1), '{"raza": "Droughtmaster (DM)", "peso_no_registrado": true}'::jsonb) ON CONFLICT (rfid_siniiga) DO UPDATE SET numero_fuego = EXCLUDED.numero_fuego, brand_id = COALESCE(EXCLUDED.brand_id, cattle_livestock.brand_id), metadata = cattle_livestock.metadata || EXCLUDED.metadata;

COMMIT;
