version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/hosting3m-workspace"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/infrastructure/upload-file/app"
    schedule:
      interval: "weekly"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/microservices/jwt-service"
    schedule:
      interval: "weekly"
    target-branch: "develop"
